#!/usr/bin/env python3
"""Regenerate lib/emoji-data.ts from the Unicode database.

    python3 scripts/generate-emoji-data.py

WHY GENERATED AND NOT A DEPENDENCY. The composer needs the full emoji set with
searchable names. Every package that offers that (emoji-mart and friends) ships
hundreds of kilobytes and its own React surface, and perf-watch has cmngrdn's
bundle growing ~4%/week already. Python's `unicodedata` is in the standard
library and carries the official name of every codepoint, so the data is free
and the output is a plain array with no runtime attached — currently ~1,780
entries, ~16 KB gzipped, and lazy-loaded so the initial bundle pays nothing.

WHY NOT HAND-MAINTAINED. The previous picker was a curated 48. Growing that by
hand to cover "all of them" would be a list nobody can review and that silently
falls behind each Unicode release. Regenerating takes a second and the diff is
readable.

SCOPE, deliberately. Single-codepoint emoji only. Skin-tone modifiers, flags
(regional indicator pairs) and ZWJ sequences like 👨‍👩‍👧 are excluded: they are
multi-codepoint, they roughly triple the payload, and — the reason that actually
decides it — every one of them pushes an SMS body into UCS-2 the same way a
plain emoji does while costing more characters, and this picker's whole premise
is that the cost of a glyph is visible at the moment you choose it.
"""
import json
import pathlib
import unicodedata

# Blocks that are emoji-bearing. 2600–27BF also holds dingbats and arrows, which
# is where entries like "double curly loop" come from — harmless, and they only
# ever surface if somebody searches the word.
RANGES = [
    (0x1F300, 0x1F5FF),  # Misc Symbols and Pictographs
    (0x1F600, 0x1F64F),  # Emoticons
    (0x1F680, 0x1F6FF),  # Transport and Map
    (0x1F900, 0x1F9FF),  # Supplemental Symbols and Pictographs
    (0x1FA70, 0x1FAFF),  # Symbols and Pictographs Extended-A
    (0x2600, 0x26FF),    # Misc Symbols
    (0x2700, 0x27BF),    # Dingbats
]

rows: list[tuple[str, str]] = []
for lo, hi in RANGES:
    for cp in range(lo, hi + 1):
        ch = chr(cp)
        try:
            name = unicodedata.name(ch)
        except ValueError:
            continue  # unassigned codepoint — the gaps are real and expected
        if "REGIONAL INDICATOR" in name:
            continue  # flags are pairs; see SCOPE above
        rows.append((ch, name.lower()))

payload = json.dumps(rows, ensure_ascii=False, separators=(",", ":"))

out = pathlib.Path(__file__).resolve().parent.parent / "lib/emoji-data.ts"
out.parent.mkdir(parents=True, exist_ok=True)
out.write_text(
    "// GENERATED by scripts/generate-emoji-data.py — do not edit by hand.\n"
    "// Regenerate: python3 scripts/generate-emoji-data.py\n"
    "//\n"
    "// [glyph, official Unicode name] for every single-codepoint emoji.\n"
    "// Imported dynamically by EmojiPicker so this never enters the initial\n"
    "// bundle — it loads the first time someone types in the emoji search.\n"
    "//\n"
    f"// {len(rows)} entries.\n"
    "export const EMOJI_DATA: [string, string][] = " + payload + ";\n",
    encoding="utf-8",
)
print(f"wrote {out.relative_to(out.parent.parent.parent)} — {len(rows)} entries, {len(payload):,} bytes")
